#pragma checksum "C:\Code\CodeMazeBlog\CodeMazeSourceCode\MVCSeries\Part7\WorkingWithFilters\Views\Shared\CustomError.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "de56686a08918ab44cd0d59a2b8e22c1caeb31b6"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Views_Shared_CustomError), @"mvc.1.0.view", @"/Views/Shared/CustomError.cshtml")]
[assembly:global::Microsoft.AspNetCore.Mvc.Razor.Compilation.RazorViewAttribute(@"/Views/Shared/CustomError.cshtml", typeof(AspNetCore.Views_Shared_CustomError))]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#line 1 "C:\Code\CodeMazeBlog\CodeMazeSourceCode\MVCSeries\Part7\WorkingWithFilters\Views\_ViewImports.cshtml"
using WorkingWithFilters;

#line default
#line hidden
#line 2 "C:\Code\CodeMazeBlog\CodeMazeSourceCode\MVCSeries\Part7\WorkingWithFilters\Views\_ViewImports.cshtml"
using WorkingWithFilters.Models;

#line default
#line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"de56686a08918ab44cd0d59a2b8e22c1caeb31b6", @"/Views/Shared/CustomError.cshtml")]
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"f43a59717ec89768bb5907267fee1a551aab39ed", @"/Views/_ViewImports.cshtml")]
    public class Views_Shared_CustomError : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<dynamic>
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
#line 1 "C:\Code\CodeMazeBlog\CodeMazeSourceCode\MVCSeries\Part7\WorkingWithFilters\Views\Shared\CustomError.cshtml"
  
    ViewData["Title"] = "CustomError";
    var exception = ViewData["Exception"] as Exception;

#line default
#line hidden
            BeginContext(104, 39, true);
            WriteLiteral("\r\n<h1>An Error has Occurred</h1>\r\n\r\n<p>");
            EndContext();
            BeginContext(144, 17, false);
#line 8 "C:\Code\CodeMazeBlog\CodeMazeSourceCode\MVCSeries\Part7\WorkingWithFilters\Views\Shared\CustomError.cshtml"
Write(exception.Message);

#line default
#line hidden
            EndContext();
            BeginContext(161, 4, true);
            WriteLiteral("</p>");
            EndContext();
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<dynamic> Html { get; private set; }
    }
}
#pragma warning restore 1591
