#pragma checksum "C:\Code\CodeMazeBlog\CodeMazeSourceCode\MVCSeries\Part3\WorkingWithViews\Views\Shared\_Authors.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "e8808f0c9802672eaeda9471c50bcde70117fedd"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Views_Shared__Authors), @"mvc.1.0.view", @"/Views/Shared/_Authors.cshtml")]
[assembly:global::Microsoft.AspNetCore.Mvc.Razor.Compilation.RazorViewAttribute(@"/Views/Shared/_Authors.cshtml", typeof(AspNetCore.Views_Shared__Authors))]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#line 1 "C:\Code\CodeMazeBlog\CodeMazeSourceCode\MVCSeries\Part3\WorkingWithViews\Views\_ViewImports.cshtml"
using WorkingWithViews;

#line default
#line hidden
#line 2 "C:\Code\CodeMazeBlog\CodeMazeSourceCode\MVCSeries\Part3\WorkingWithViews\Views\_ViewImports.cshtml"
using WorkingWithViews.Models;

#line default
#line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"e8808f0c9802672eaeda9471c50bcde70117fedd", @"/Views/Shared/_Authors.cshtml")]
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"2a75bc5ded6aabe442388b3384d0a94eeab4ca29", @"/Views/_ViewImports.cshtml")]
    public class Views_Shared__Authors : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<dynamic>
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            BeginContext(0, 87, true);
            WriteLiteral("<h3>Authors</h3>\r\n\r\n<p>This section is used to display information about authors.</p>\r\n");
            EndContext();
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<dynamic> Html { get; private set; }
    }
}
#pragma warning restore 1591
