#pragma checksum "C:\Code\CodeMazeBlog\CodeMazeSourceCode\MVCSeries\Part7\WorkingWithFilters\Views\Home\TestResultFilter.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "dd918f2b480fd087afaeecf0b447e976dc14a43a"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Views_Home_TestResultFilter), @"mvc.1.0.view", @"/Views/Home/TestResultFilter.cshtml")]
[assembly:global::Microsoft.AspNetCore.Mvc.Razor.Compilation.RazorViewAttribute(@"/Views/Home/TestResultFilter.cshtml", typeof(AspNetCore.Views_Home_TestResultFilter))]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#line 1 "C:\Code\CodeMazeBlog\CodeMazeSourceCode\MVCSeries\Part7\WorkingWithFilters\Views\_ViewImports.cshtml"
using WorkingWithFilters;

#line default
#line hidden
#line 2 "C:\Code\CodeMazeBlog\CodeMazeSourceCode\MVCSeries\Part7\WorkingWithFilters\Views\_ViewImports.cshtml"
using WorkingWithFilters.Models;

#line default
#line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"dd918f2b480fd087afaeecf0b447e976dc14a43a", @"/Views/Home/TestResultFilter.cshtml")]
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"f43a59717ec89768bb5907267fee1a551aab39ed", @"/Views/_ViewImports.cshtml")]
    public class Views_Home_TestResultFilter : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<dynamic>
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            BeginContext(0, 2, true);
            WriteLiteral("\r\n");
            EndContext();
#line 2 "C:\Code\CodeMazeBlog\CodeMazeSourceCode\MVCSeries\Part7\WorkingWithFilters\Views\Home\TestResultFilter.cshtml"
  
    ViewData["Title"] = "TestResultFilter";

#line default
#line hidden
            BeginContext(54, 31, true);
            WriteLiteral("\r\n<h1>TestResultFilter</h1>\r\n\r\n");
            EndContext();
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<dynamic> Html { get; private set; }
    }
}
#pragma warning restore 1591
